#!/bin/bash
#
# Concatenates every migration into one file for pasting into the Supabase SQL Editor.
# Generated on demand so it cannot drift from supabase/migrations/.
#
#   ./supabase/bundle.sh > csw-schema-all.sql
#
set -eu
cd "$(dirname "$0")/.."

cat <<'HDR'
-- ============================================================================
-- Chicken Sandwich Wars - complete schema
--
-- Every migration in supabase/migrations/, concatenated in order. Paste the
-- whole file into the Supabase SQL Editor and press Run once.
--
-- Wrapped in a single transaction: if any statement fails, everything rolls
-- back and the database is left exactly as it was. There is no half-applied
-- state to clean up, so a failure is safe to retry after a fix.
--
-- Generated by supabase/bundle.sh - do not edit. Edit the migrations instead.
-- ============================================================================

begin;
HDR

for f in supabase/migrations/*.sql; do
  printf '\n\n-- ==== %s %s\n\n' "$(basename "$f")" "$(printf '=%.0s' $(seq 1 $((58 - ${#f}))))"
  cat "$f"
done

cat <<'FTR'


commit;

-- Sanity check. Expect: 38 public tables, 4 intake, 1 audit.
select table_schema, count(*) as tables
from information_schema.tables
where table_schema in ('public','intake','audit') and table_type = 'BASE TABLE'
group by table_schema order by table_schema;
FTR
