'use strict';
/**
 * CSW Intelligence Desk.
 *
 * No framework and no build step, in keeping with the rest of the project: the site is
 * static HTML generated by a dependency-free Node script, and an admin screen that
 * needed a bundler would be the only thing in the repository that did.
 *
 * The shape of it:
 *
 *   sign in   Supabase Auth, by emailed code. The browser holds a normal user session
 *             and nothing more privileged; every request to /api/admin carries that
 *             token, and Postgres decides what comes back.
 *   queue     everything waiting for a decision, from the desk and from agents alike
 *   add       a form generated from the database's own column metadata, so it cannot
 *             drift from the schema
 *   data      canonical records, each with a "propose an edit" that lands back in the
 *             queue rather than writing anything
 *
 * Nothing in this file writes canonical data. It cannot: the only write operations the
 * API exposes are review_submit and review_decide.
 */
(function () {
  const API = '/api/admin';
  const SESSION_KEY = 'csw.desk.session';

  /* ---------- tiny helpers ---------- */
  const $ = (s, r) => (r || document).querySelector(s);
  const h = (v) => String(v == null ? '' : v)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  const el = (html) => { const t = document.createElement('template'); t.innerHTML = html.trim(); return t.content.firstElementChild; };

  const TITLE = { pending: 'Waiting for you', needs_verification: 'Needs verification',
                  applied: 'Approved & live', rejected: 'Rejected', duplicate: 'Marked duplicate',
                  withdrawn: 'Withdrawn', approved: 'Approved' };
  const statusLabel = (s) => TITLE[s] || s;

  const ago = (iso) => {
    if (!iso) return '';
    const s = (Date.now() - new Date(iso).getTime()) / 1000;
    if (s < 60) return 'just now';
    if (s < 3600) return `${Math.floor(s / 60)}m ago`;
    if (s < 86400) return `${Math.floor(s / 3600)}h ago`;
    if (s < 86400 * 30) return `${Math.floor(s / 86400)}d ago`;
    return new Date(iso).toLocaleDateString();
  };

  /* Values come back from Postgres as strings, numbers, booleans, arrays and objects.
     A diff cell that says [object Object] is worse than useless, so everything is
     rendered explicitly and "not set" is a visible state rather than an empty cell. */
  const show = (v) => {
    if (v === null || v === undefined || v === '') return '—';
    if (typeof v === 'boolean') return v ? 'yes' : 'no';
    if (Array.isArray(v)) return v.length ? v.join(', ') : '—';
    if (typeof v === 'object') return JSON.stringify(v);
    const s = String(v);
    /* Numeric columns arrive as '2450000.0000'. Nobody reads that. */
    if (/^-?\d+\.0+$/.test(s)) return Number(s).toLocaleString();
    if (/^-?\d{4,}(\.\d+)?$/.test(s)) return Number(s).toLocaleString();
    return s;
  };

  let toastTimer = null;
  function toast(message, isError) {
    const old = $('.toast'); if (old) old.remove();
    const t = el(`<div class="toast${isError ? ' err' : ''}">${h(message)}</div>`);
    document.body.appendChild(t);
    clearTimeout(toastTimer);
    toastTimer = setTimeout(() => t.remove(), isError ? 7000 : 3500);
  }

  /* ---------- state ---------- */
  const state = {
    cfg: null, session: null, me: null, targets: null, stats: null,
    queue: [], selected: null, filters: { status: 'pending,needs_verification' }
  };

  /* ---------- session ---------- */
  const loadSession = () => {
    try { return JSON.parse(localStorage.getItem(SESSION_KEY) || 'null'); } catch { return null; }
  };
  const saveSession = (s) => {
    state.session = s;
    try {
      if (s) localStorage.setItem(SESSION_KEY, JSON.stringify(s));
      else localStorage.removeItem(SESSION_KEY);
    } catch { /* private browsing: the session simply does not survive a reload */ }
  };

  async function auth(path, body) {
    const r = await fetch(`${state.cfg.url}/auth/v1/${path}`, {
      method: 'POST',
      headers: { apikey: state.cfg.anonKey, 'Content-Type': 'application/json' },
      body: JSON.stringify(body)
    });
    const data = await r.json().catch(() => ({}));
    if (!r.ok) throw new Error(data.msg || data.error_description || data.message || 'Sign-in failed.');
    return data;
  }

  const storeToken = (d) => saveSession({
    access_token: d.access_token, refresh_token: d.refresh_token,
    expires_at: Date.now() + ((d.expires_in || 3600) * 1000), email: d.user && d.user.email
  });

  async function refresh() {
    if (!state.session || !state.session.refresh_token) return false;
    try {
      const d = await auth('token?grant_type=refresh_token',
        { refresh_token: state.session.refresh_token });
      storeToken(d);
      return true;
    } catch { saveSession(null); return false; }
  }

  /* ---------- api ---------- */
  async function api(op, args, retried) {
    if (state.session && state.session.expires_at - Date.now() < 60000) await refresh();
    const r = await fetch(API, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...(state.session ? { Authorization: `Bearer ${state.session.access_token}` } : {})
      },
      body: JSON.stringify({ op, ...(args || {}) })
    });
    const data = await r.json().catch(() => ({ ok: false, error: 'The server did not reply with JSON.' }));
    if (r.status === 401 && !retried && await refresh()) return api(op, args, true);
    if (!r.ok || !data.ok) {
      const e = new Error(data.error || `Request failed (${r.status})`);
      e.status = r.status;
      throw e;
    }
    return data;
  }

  /* ---------- sign in ---------- */
  function renderSignIn(message) {
    $('#app').hidden = true;
    $('#signin').hidden = false;
    const box = $('#signinBody');

    if (!state.cfg || !state.cfg.configured) {
      box.innerHTML = `<div class="msg err"><b>Not configured</b>
        This deployment has no Supabase credentials. Set <code>SUPABASE_URL</code> and
        <code>SUPABASE_ANON_KEY</code> in the Vercel project, then redeploy.</div>`;
      return;
    }

    box.innerHTML = `
      ${message ? `<div class="msg ${message.kind || 'err'}">${message.html}</div>` : ''}
      <form id="emailForm">
        <div class="field">
          <label for="email">Work email</label>
          <input id="email" type="email" autocomplete="email" required
                 placeholder="you@example.com" value="${h((loadSession() || {}).email || '')}">
          <div class="hint">We email a six-digit code. There is no password to remember.</div>
        </div>
        <button class="btn-primary" style="width:100%" type="submit">Email me a code</button>
      </form>`;

    $('#emailForm').addEventListener('submit', async (e) => {
      e.preventDefault();
      const email = $('#email').value.trim().toLowerCase();
      const btn = $('#emailForm button');
      btn.disabled = true; btn.textContent = 'Sending…';
      try {
        /* create_user:false matters: without it this endpoint is an open sign-up form
           for anyone who finds the URL. Desk accounts are created in the Supabase
           dashboard, and access is granted from Settings once they have signed in. */
        await auth('otp', { email, create_user: false });
        renderCodeForm(email);
      } catch (err) {
        const unknown = /signups not allowed|not found|invalid/i.test(err.message);
        renderSignIn({ kind: 'err', html: unknown
          ? `<b>No desk account for that address</b> An admin creates accounts in Supabase
             under Authentication → Users, then grants access from the desk's Settings screen.`
          : `<b>Could not send the code</b> ${h(err.message)}` });
      }
    });
  }

  function renderCodeForm(email) {
    $('#signinBody').innerHTML = `
      <div class="msg info"><b>Check ${h(email)}</b> The code is good for one hour.</div>
      <form id="codeForm">
        <div class="field">
          <label for="code">Six-digit code</label>
          <input id="code" inputmode="numeric" autocomplete="one-time-code" required
                 pattern="[0-9]{6}" maxlength="6" placeholder="000000" style="font-family:var(--mono);
                 font-size:20px;letter-spacing:.3em;text-align:center">
        </div>
        <button class="btn-primary" style="width:100%" type="submit">Sign in</button>
        <button class="btn-ghost" style="width:100%;margin-top:8px" type="button" id="backBtn">
          Use a different address</button>
      </form>`;
    $('#code').focus();
    $('#backBtn').addEventListener('click', () => renderSignIn());
    $('#codeForm').addEventListener('submit', async (e) => {
      e.preventDefault();
      const btn = $('#codeForm button'); btn.disabled = true; btn.textContent = 'Checking…';
      try {
        storeToken(await auth('verify', { email, token: $('#code').value.trim(), type: 'email' }));
        await boot();
      } catch (err) {
        btn.disabled = false; btn.textContent = 'Sign in';
        toast(err.message || 'That code did not work.', true);
      }
    });
  }

  /* A signed-in account with no staff row. Deliberately not fixable from here: anything
     that could grant the first admin would be a door into the desk. One line of SQL,
     pasted where only the owner can paste it, is the right size of key. */
  function renderNoAccess(me) {
    $('#app').hidden = true;
    $('#signin').hidden = false;
    $('#signinBody').innerHTML = `
      <div class="msg warn"><b>Signed in, but no desk access</b>
        ${h(me.email)} has a Supabase account with no role on the desk.</div>
      <p class="note">If you are the owner setting this up for the first time, run this in the
        Supabase SQL editor:</p>
      <div class="secret">insert into public.staff_profiles (user_id, role, full_name)
values ('${h(me.user_id)}', 'admin', '${h((me.email || '').split('@')[0])}');</div>
      <p class="note" style="margin-top:12px">Otherwise ask an admin to add you from
        Settings → Desk access. Then reload.</p>
      <div class="row" style="margin-top:16px">
        <button class="btn-ghost" onclick="location.reload()">Reload</button>
        <button class="btn-ghost" id="soBtn">Sign out</button>
      </div>`;
    $('#soBtn').addEventListener('click', signOut);
  }

  function signOut() {
    saveSession(null);
    location.hash = '';
    location.reload();
  }

  /* ---------- navigation ---------- */
  const NAV = [
    ['overview', 'Overview', '◈'],
    ['queue', 'Review queue', '⊙', 'pending'],
    ['add', 'Add intelligence', '＋'],
    ['runs', 'Research runs', '⚗'],
    ['data', 'Intelligence', '▤'],
    ['leads', 'Leads', '✉', 'new_leads'],
    ['settings', 'Settings', '⚙']
  ];

  function renderNav(active) {
    $('#railnav').innerHTML = NAV.map(([key, label, ico, statKey]) => {
      const n = statKey && state.stats ? state.stats[statKey] : null;
      const tally = n ? `<span class="tally${key === 'queue' ? '' : ' quiet'}">${n}</span>` : '';
      return `<a href="#/${key}" class="${key === active ? 'on' : ''}">
                <span class="ico">${ico}</span>${h(label)}${tally}</a>`;
    }).join('');
  }

  const setHead = (title, sub) => {
    $('#viewTitle').textContent = title;
    $('#viewSub').textContent = sub || '';
  };

  /* ---------- shared bits ---------- */
  const statusTag = (s) => `<span class="tag ${h(s)}">${h(statusLabel(s))}</span>`;
  const whoTag = (item) => item.submitter_kind === 'agent'
    ? `<span class="tag agent">agent${item.agent_name ? ' · ' + h(item.agent_name) : ''}</span>`
    : `<span class="tag">${h(item.submitted_by_label || 'desk')}</span>`;
  const visTag = (v) => (v && v !== 'public' ? `<span class="tag ${h(v)}">${h(v)}</span>` : '');
  const confTag = (c) => (c && c !== 'medium' ? `<span class="tag ${h(c)}">${h(c)} confidence</span>` : '');

  function queueRow(item, selectedId) {
    return `<button class="item ${item.id === selectedId ? 'on' : ''}" data-id="${h(item.id)}">
      <div class="t">${h(item.title)}</div>
      <div class="m">
        ${statusTag(item.status)}
        <span>${h(item.target_label)}</span>
        ${item.entity_label ? `<span class="dot">·</span><span>${h(item.entity_label)}</span>` : ''}
        ${whoTag(item)}
        ${visTag(item.visibility)}
        ${Number(item.open_match_count) ? '<span class="tag pending">possible duplicate</span>' : ''}
        ${Number(item.source_count) === 0 ? '<span class="tag needs_verification">no source</span>' : ''}
        <span class="dot">·</span><span>${h(ago(item.created_at))}</span>
      </div></button>`;
  }

  /* The before/after table. The left column is the record as it stands right now, read
     back live — not the snapshot taken when the proposal was made, because the whole
     point of showing it is to catch the case where those two differ. */
  function diffTable(item, current) {
    const keys = Object.keys(item.payload || {});
    if (!keys.length) return '<p class="note">This proposal has no fields.</p>';
    const isInsert = item.operation === 'insert';
    const rows = keys.map((k) => {
      const proposed = item.payload[k];
      const now = current ? current[k] : (item.baseline || {})[k];
      const changed = isInsert || String(show(now)) !== String(show(proposed));
      return `<tr class="${changed ? '' : 'same'}">
        <td>${h(k)}</td>
        <td class="${changed && !isInsert ? 'was' : ''}">${isInsert ? '—' : h(show(now))}</td>
        <td class="${changed ? (isInsert ? 'new' : 'now') : ''}">${h(show(proposed))}</td>
      </tr>`;
    }).join('');
    return `<div class="scroller"><table class="diff">
      <thead><tr><th>Field</th><th>${isInsert ? 'Today' : 'Now'}</th><th>Proposed</th></tr></thead>
      <tbody>${rows}</tbody></table></div>`;
  }

  function sourceBlock(sources) {
    if (!sources.length) {
      return `<div class="msg warn"><b>No source</b> Nothing here can be published until
        someone can say where it came from.</div>`;
    }
    return sources.map((s) => {
      const known = s.source || {};
      const url = s.url || known.url;
      const publisher = s.publisher || known.publisher || 'Unattributed';
      const title = s.title || known.title || url;
      return `<div class="card" style="padding:var(--sp-4);margin-bottom:var(--sp-2)">
        <div style="font-weight:600;font-size:13.5px">${h(publisher)}</div>
        <div class="note">${h(title)}${s.date_label || known.date_label ? ' · ' + h(s.date_label || known.date_label) : ''}</div>
        ${url ? `<div style="margin-top:6px"><a href="${h(url)}" target="_blank" rel="noopener noreferrer">${h(url)}</a></div>` : ''}
        ${s.quote ? `<div class="note" style="margin-top:8px;border-left:2px solid var(--line-2);padding-left:10px">“${h(s.quote)}”</div>` : ''}
        ${known.key ? `<div class="note mono" style="margin-top:6px">already in the source registry as ${h(known.key)}</div>`
                    : '<div class="note" style="margin-top:6px">will be added to the source registry when approved</div>'}
      </div>`;
    }).join('');
  }

  /* ---------- views ---------- */
  const views = {};

  views.overview = async () => {
    setHead('Overview', 'What is waiting, and what changed');
    const [{ stats }, { items }] = await Promise.all([
      api('stats'), api('queue', { status: 'pending,needs_verification', limit: 8 })
    ]);
    state.stats = stats;
    renderNav('overview');

    const tile = (n, label, sub, href, alert) =>
      `<a class="stat${alert && n ? ' alert' : ''}" href="${href}">
        <div class="n${n ? '' : ' zero'}">${n}</div><div class="l">${h(label)}</div>
        ${sub ? `<div class="s">${h(sub)}</div>` : ''}</a>`;

    $('#view').innerHTML = `
      <div class="grid g4" style="margin-bottom:var(--sp-6)">
        ${tile(stats.pending, 'Waiting for you', 'proposals to decide', '#/queue', true)}
        ${tile(stats.needs_verification, 'Needs verification', 'unsourced or unsure', '#/queue?status=needs_verification', true)}
        ${tile(stats.new_leads, 'New leads', 'from the site forms', '#/leads', true)}
        ${tile(stats.open_matches, 'Possible duplicates', 'flagged, not merged', '#/queue', true)}
      </div>
      <div class="grid g4" style="margin-bottom:var(--sp-6)">
        ${tile(stats.applied_7d, 'Approved this week', 'now live', '#/queue?status=applied')}
        ${tile(stats.agent_runs_7d, 'Agent runs this week', 'research submitted', '#/runs')}
        ${tile(stats.unverified_sources, 'Sources to check', `of ${stats.sources_total} against the primary document`, '#/data?table=public.sources')}
        ${tile(stats.internal_records, 'Internal records', 'held back from the site', '#/data')}
      </div>
      <div class="row" style="justify-content:space-between;margin-bottom:var(--sp-3)">
        <h2>Next in the queue</h2>
        <a href="#/queue">See all →</a>
      </div>
      <div class="list">${items.length ? items.map((i) => queueRow(i)).join('')
        : `<div class="empty"><b>Nothing waiting</b>Everything submitted has been decided.</div>`}</div>`;

    $('#view').querySelectorAll('.item').forEach((b) =>
      b.addEventListener('click', () => { location.hash = `#/queue?id=${b.dataset.id}`; }));
  };

  views.queue = async (params) => {
    setHead('Review queue', 'Nothing here has touched the site yet');
    const status = params.get('status') || state.filters.status;
    state.filters.status = status;
    const { items } = await api('queue', {
      status, target: params.get('target') || undefined, q: params.get('q') || undefined,
      submitter: params.get('submitter') || undefined, limit: 100
    });
    state.queue = items;

    const chip = (val, label) =>
      `<button class="chip ${status === val ? 'on' : ''}" data-status="${h(val)}">${h(label)}</button>`;

    $('#view').innerHTML = `
      <div class="row" style="margin-bottom:var(--sp-4)">
        <div class="chips">
          ${chip('pending,needs_verification', 'Open')}
          ${chip('pending', 'Waiting for you')}
          ${chip('needs_verification', 'Needs verification')}
          ${chip('applied', 'Approved')}
          ${chip('rejected,duplicate,withdrawn', 'Closed')}
          ${chip('all', 'Everything')}
        </div>
        <div class="searchcell" style="margin-left:auto;min-width:200px">
          <input id="qSearch" type="search" placeholder="Search titles and subjects"
                 value="${h(params.get('q') || '')}">
        </div>
      </div>
      <div class="split">
        <div class="list" id="qList">
          ${items.length ? items.map((i) => queueRow(i, params.get('id'))).join('')
            : `<div class="empty"><b>Nothing here</b>No proposals match this filter.</div>`}
        </div>
        <div id="qDetail">${items.length
          ? '<div class="card"><p class="note">Select a proposal to review it. <b>j</b> and <b>k</b> move, <b>a</b> approves, <b>r</b> rejects, <b>v</b> asks for verification.</p></div>'
          : ''}</div>
      </div>`;

    $('#view').querySelectorAll('.chip').forEach((c) => c.addEventListener('click', () => {
      location.hash = `#/queue?status=${encodeURIComponent(c.dataset.status)}`;
    }));
    let searchTimer;
    $('#qSearch').addEventListener('input', (e) => {
      clearTimeout(searchTimer);
      const v = e.target.value;
      searchTimer = setTimeout(() => {
        location.hash = `#/queue?status=${encodeURIComponent(status)}${v ? '&q=' + encodeURIComponent(v) : ''}`;
      }, 350);
    });
    $('#view').querySelectorAll('.item').forEach((b) =>
      b.addEventListener('click', () => selectItem(b.dataset.id)));

    if (params.get('id')) await selectItem(params.get('id'));
  };

  async function selectItem(id) {
    state.selected = id;
    $('#view').querySelectorAll('.item').forEach((b) =>
      b.classList.toggle('on', b.dataset.id === id));
    const box = $('#qDetail');
    if (!box) return;
    box.innerHTML = '<div class="card loading"><span class="spin"></span></div>';
    try {
      const d = await api('item', { id });
      box.innerHTML = detailHtml(d);
      wireDetail(box, d);
    } catch (e) {
      box.innerHTML = `<div class="msg err">${h(e.message)}</div>`;
    }
  }

  function detailHtml(d) {
    const { item, sources, matches, events, validation, current } = d;
    const errors = (validation && validation.errors) || [];
    const warnings = (validation && validation.warnings) || [];
    const stale = (validation && validation.stale) || [];
    const open = item.status === 'pending' || item.status === 'needs_verification';

    const problems = [
      errors.length ? `<div class="msg err"><b>Cannot be approved as it stands</b>
        <ul>${errors.map((x) => `<li>${h(x)}</li>`).join('')}</ul></div>` : '',
      stale.length ? `<div class="msg warn"><b>The record moved while this waited</b>
        <ul>${stale.map((x) => `<li>${h(x)}</li>`).join('')}</ul>
        Approving now needs the override below.</div>` : '',
      warnings.length ? `<div class="msg warn"><b>Worth a look</b>
        <ul>${warnings.map((x) => `<li>${h(x)}</li>`).join('')}</ul></div>` : ''
    ].join('');

    const matchHtml = matches.length ? `
      <div class="section">
        <div class="kicker">Possible duplicates — flagged, never merged</div>
        ${matches.map((m) => `<div class="row" style="justify-content:space-between;
             border:1px solid var(--line);border-radius:var(--radius);padding:10px 12px;margin-bottom:6px">
          <div><div style="font-weight:600;font-size:13.5px">${h(m.candidate_label || m.candidate_id)}</div>
            <div class="note">${h(m.reason)}${m.similarity ? ` · ${Math.round(m.similarity * 100)}% match` : ''}</div></div>
          ${m.resolution === 'unresolved'
            ? `<div class="row" style="gap:6px">
                 <button class="btn-sm" data-match="${h(m.id)}" data-res="different">Different</button>
                 <button class="btn-sm" data-match="${h(m.id)}" data-res="same">Same record</button></div>`
            : `<span class="tag">${h(m.resolution)}</span>`}
        </div>`).join('')}
      </div>` : '';

    return `<div class="detail">
      <div class="head">
        <div class="row" style="gap:6px;margin-bottom:8px">
          ${statusTag(item.status)}${whoTag(item)}${visTag(item.visibility)}${confTag(item.confidence)}
        </div>
        <h2>${h(item.title)}</h2>
        <div class="note" style="margin-top:6px">
          ${item.operation === 'insert' ? 'New' : 'Edit to an existing'} ${h(item.target_label)}
          ${item.entity_label ? ` · ${h(item.entity_label)}` : ''} · submitted ${h(ago(item.created_at))}
          ${item.batch_title ? ` · from <a href="#/runs?id=${h(item.batch_id)}">${h(item.batch_title)}</a>` : ''}
        </div>
      </div>
      <div class="body">
        ${problems}
        ${item.rationale ? `<div class="section"><div class="kicker">Why</div>
          <p style="margin:0">${h(item.rationale)}</p></div>` : ''}
        <div class="section">
          <div class="kicker">${item.operation === 'insert' ? 'What would be created' : 'Before and after'}</div>
          ${diffTable(item, current)}
        </div>
        <div class="section">
          <div class="kicker">Provenance</div>
          ${sourceBlock(sources)}
        </div>
        ${matchHtml}
        <div class="section">
          <div class="kicker">History</div>
          <dl class="kv">${events.map((e) => `<dt>${h(ago(e.at))}</dt>
            <dd>${h(e.action)}${e.actor_label ? ` · ${h(e.actor_label)}` : ''}${e.note ? ` — ${h(e.note)}` : ''}</dd>`).join('')}</dl>
        </div>
        ${item.review_note ? `<div class="msg info"><b>Reviewer note</b>${h(item.review_note)}</div>` : ''}
      </div>
      ${open && state.me.can_edit ? `<div class="actions">
        <button class="btn-primary" data-act="approve" ${errors.length ? 'disabled' : ''}>
          ${stale.length ? 'Approve anyway' : 'Approve'}</button>
        <button data-act="edit">Edit & approve</button>
        <button data-act="needs_verification">Needs verification</button>
        <button class="btn-danger" data-act="reject">Reject</button>
      </div>` : ''}
      ${open && !state.me.can_edit ? `<div class="actions">
        <span class="note">Your role can propose but not approve.</span></div>` : ''}
    </div>`;
  }

  function wireDetail(box, d) {
    const { item, validation } = d;
    box.querySelectorAll('[data-match]').forEach((b) => b.addEventListener('click', async () => {
      await api('resolveMatch', { id: b.dataset.match, resolution: b.dataset.res });
      toast('Noted.');
      selectItem(item.id);
    }));

    box.querySelectorAll('[data-act]').forEach((b) => b.addEventListener('click', async () => {
      const act = b.dataset.act;
      if (act === 'edit') return editAndApprove(item);
      let note = null;
      if (act === 'reject' || act === 'needs_verification') {
        note = prompt(act === 'reject'
          ? 'Why is this being rejected? The reason is kept with the proposal.'
          : 'What needs checking?');
        if (note === null) return;
      }
      const force = ((validation && validation.stale) || []).length > 0;
      if (force && !confirm('The record changed since this was proposed. Approve anyway?')) return;
      b.disabled = true;
      try {
        await api('decide', { id: item.id, decision: act, note, force });
        toast(act === 'approve' ? 'Approved — it is live.' : `Marked ${statusLabel(act).toLowerCase()}.`);
        advance(item.id);
      } catch (e) { toast(e.message, true); b.disabled = false; }
    }));
  }

  /* Editing before approving keeps the reviewer's correction in the queue rather than
     losing it: the override is merged into the payload and recorded as an event. */
  function editAndApprove(item) {
    const box = $('#qDetail');
    const fields = Object.keys(item.payload);
    box.querySelector('.actions').outerHTML = `
      <div class="actions" style="flex-direction:column;align-items:stretch">
        <div class="kicker" style="margin:0 0 8px">Correct the values, then approve</div>
        <div id="overrideFields" style="width:100%">
          ${fields.map((k) => `<div class="field" style="margin-bottom:10px">
            <label>${h(k)}</label>
            <input data-k="${h(k)}" value="${h(show(item.payload[k]) === '—' ? '' : item.payload[k])}">
          </div>`).join('')}
        </div>
        <div class="row">
          <button class="btn-primary" id="saveApprove">Approve with these values</button>
          <button class="btn-ghost" id="cancelEdit">Cancel</button>
        </div>
      </div>`;
    $('#cancelEdit').addEventListener('click', () => selectItem(item.id));
    $('#saveApprove').addEventListener('click', async () => {
      const override = {};
      $('#overrideFields').querySelectorAll('input').forEach((i) => {
        const before = item.payload[i.dataset.k];
        const raw = i.value;
        if (String(before == null ? '' : before) === raw) return;
        override[i.dataset.k] = raw === '' ? null
          : (typeof before === 'number' && raw !== '' && !isNaN(Number(raw)) ? Number(raw) : raw);
      });
      try {
        await api('decide', { id: item.id, decision: 'approve', override, force: true });
        toast('Approved with your corrections.');
        advance(item.id);
      } catch (e) { toast(e.message, true); }
    });
  }

  /* After a decision, move to the next proposal rather than back to an empty pane —
     a queue is worked through, not dipped into. */
  function advance(decidedId) {
    const idx = state.queue.findIndex((i) => i.id === decidedId);
    const next = state.queue[idx + 1];
    state.queue = state.queue.filter((i) => i.id !== decidedId);
    const row = $(`.item[data-id="${decidedId}"]`);
    if (row) row.remove();
    if (next) selectItem(next.id);
    else {
      $('#qDetail').innerHTML = `<div class="card"><div class="empty"><b>Queue clear</b>
        Nothing else is waiting under this filter.</div></div>`;
    }
    api('stats').then(({ stats }) => { state.stats = stats; renderNav('queue'); });
  }

  /* ---------- add intelligence ---------- */
  const LOOKUP_KIND = { brands: 'brand', companies: 'company', markets: 'market',
                        properties: 'property', sources: 'source', metrics: 'metric',
                        transactions: 'transaction' };
  const TOKEN_KIND = { brands: '@brand', companies: '@company', markets: '@market',
                       properties: '@property', sources: '@source', transactions: '@transaction' };

  const prettyName = (n) => n.replace(/_(md|usd|pct|id|at|on)$/, (m) => ({
    _md: '', _usd: ' (USD)', _pct: ' (%)', _id: '', _at: '', _on: '' }[m]))
    .replace(/_/g, ' ').replace(/^\w/, (c) => c.toUpperCase());

  views.add = async (params) => {
    if (!state.targets) state.targets = (await api('schema')).targets;
    const table = params.get('table');
    if (!table) return renderTargetPicker();
    const target = state.targets.find((t) => t.table_name === table);
    if (!target) return renderTargetPicker();
    let current = null;
    if (params.get('id')) {
      current = (await api('records', { table, limit: 200 })).records
        .find((r) => r.id === params.get('id'));
    }
    renderAddForm(target, current);
  };

  function renderTargetPicker() {
    setHead('Add intelligence', 'Everything here goes to the review queue, including yours');
    const groups = {};
    state.targets.forEach((t) => { (groups[t.group_label] = groups[t.group_label] || []).push(t); });
    $('#view').innerHTML = `
      <div class="msg info" style="margin-bottom:var(--sp-5)">
        <b>Nothing you add here goes straight to the site.</b>
        It joins the same queue an agent's research lands in, and waits for an approval —
        yours included. That is what keeps one pair of eyes on every published figure.
      </div>
      ${Object.entries(groups).map(([g, list]) => `
        <div class="groupname">${h(g)}</div>
        <div class="targets">${list.map((t) => `
          <button class="target" data-table="${h(t.table_name)}">
            <div class="n">${h(t.label)}</div>
            <div class="d">${h(t.description || '')}</div>
          </button>`).join('')}</div>`).join('')}`;
    $('#view').querySelectorAll('.target').forEach((b) => b.addEventListener('click', () => {
      location.hash = `#/add?table=${encodeURIComponent(b.dataset.table)}`;
    }));
  }

  /* The form is generated from review_schema(), which reads pg_attribute. There is no
     field list in this file to fall out of step with the database: add a column to a
     target's allowed_columns and it appears here, with its type, its enum values and
     its foreign key already understood. */
  function fieldHtml(col, value) {
    const id = `f_${col.name}`;
    const label = `<label for="${id}">${h(prettyName(col.name))}${col.required ? ' <span style="color:var(--accent)">*</span>' : ''}</label>`;
    const hint = col.comment ? `<div class="hint">${h(col.comment.split('\n')[0])}</div>` : '';
    const v = value == null ? '' : value;

    if (col.enum_values && col.enum_values.length) {
      return `<div class="field">${label}
        <select id="${id}" data-col="${h(col.name)}" data-kind="enum">
          <option value="">—</option>
          ${col.enum_values.map((e) => `<option ${String(v) === e ? 'selected' : ''}>${h(e)}</option>`).join('')}
        </select>${hint}</div>`;
    }
    if (col.type === 'boolean') {
      return `<div class="field"><label class="checkline">
        <input type="checkbox" id="${id}" data-col="${h(col.name)}" data-kind="bool" ${v === true ? 'checked' : ''}>
        ${h(prettyName(col.name))}</label>${hint}</div>`;
    }
    /* subject_id is polymorphic — facts and entity_notes point at a brand, a company, a
       market or a category, so there is no foreign key for the catalogue to report and
       no fixed table to search. The picker reads the subject_type field beside it
       instead. Without this the only way to fill the field would be to paste a uuid,
       which is exactly the "raw database editor" this is meant not to be. */
    if (col.name === 'subject_id') {
      return `<div class="field">${label}
        <div class="picker" data-col="${h(col.name)}" data-kind="ref" data-lookup="subject"
             data-token="auto" data-value="${h(v)}">
          <input type="search" placeholder="Search — pick the subject type first…" autocomplete="off">
        </div><div class="hint">Searches whichever kind of subject you chose above.</div></div>`;
    }
    if (col.references_table && LOOKUP_KIND[col.references_table]) {
      const kind = LOOKUP_KIND[col.references_table];
      const token = TOKEN_KIND[col.references_table] || '';
      return `<div class="field">${label}
        <div class="picker" data-col="${h(col.name)}" data-kind="ref" data-lookup="${h(kind)}"
             data-token="${h(token)}" data-value="${h(v)}">
          <input type="search" placeholder="Search ${h(kind)}s…" autocomplete="off">
        </div>${hint || `<div class="hint">Start typing — this links to the real record.</div>`}</div>`;
    }
    if (/^(date)$/.test(col.type)) {
      return `<div class="field">${label}
        <input type="date" id="${id}" data-col="${h(col.name)}" data-kind="text" value="${h(v)}">${hint}</div>`;
    }
    if (/^(integer|bigint|smallint|numeric|real|double precision)/.test(col.type)) {
      return `<div class="field">${label}
        <input type="number" step="any" id="${id}" data-col="${h(col.name)}" data-kind="num" value="${h(v)}">${hint}</div>`;
    }
    if (col.type === 'jsonb' || col.type === 'json') {
      return `<div class="field">${label}
        <textarea id="${id}" data-col="${h(col.name)}" data-kind="json" placeholder="{ }">${h(v ? JSON.stringify(v) : '')}</textarea>${hint}</div>`;
    }
    if (/\[\]$/.test(col.type)) {
      return `<div class="field">${label}
        <input id="${id}" data-col="${h(col.name)}" data-kind="array" value="${h(Array.isArray(v) ? v.join(', ') : v)}">
        <div class="hint">Comma separated.</div></div>`;
    }
    if (/_md$|^(dek|summary|body|detail|notes|analysis|thesis|why|means)/.test(col.name)) {
      return `<div class="field">${label}
        <textarea id="${id}" data-col="${h(col.name)}" data-kind="text">${h(v)}</textarea>${hint}</div>`;
    }
    return `<div class="field">${label}
      <input id="${id}" data-col="${h(col.name)}" data-kind="text" value="${h(v)}">${hint}</div>`;
  }

  function renderAddForm(target, existing) {
    const editing = Boolean(existing);
    setHead(editing ? `Edit ${target.label.toLowerCase()}` : `Add ${target.label.toLowerCase()}`,
      editing ? 'Your change is a proposal, like any other' : 'Goes to the review queue');

    const row = existing ? existing.row : {};
    /* Required columns first: the fields that decide whether this can be approved at all
       should not be below the fold under twenty optional ones. */
    const cols = target.columns.slice().sort((a, b) =>
      (b.required ? 1 : 0) - (a.required ? 1 : 0) || a.ord - b.ord);

    $('#view').innerHTML = `
      <div class="row" style="margin-bottom:var(--sp-4)">
        <a class="btn btn-ghost btn-sm" href="#/add">← All types</a>
        ${editing ? `<span class="tag">editing ${h(existing.label || '')}</span>` : ''}
      </div>
      ${target.help_md ? `<div class="msg info">${h(target.help_md)}</div>` : ''}
      <form id="addForm" class="grid g2" style="align-items:start">
        <div>
          <div class="card">
            <h3>The record</h3>
            <p class="note" style="margin-bottom:var(--sp-5)">
              Fields marked <span style="color:var(--accent)">*</span> are needed before this
              can be approved. Leave anything unpublished blank — the site shows an em dash
              rather than an estimate.</p>
            ${cols.map((c) => fieldHtml(c, row[c.name])).join('')}
          </div>
        </div>
        <div>
          <div class="card" style="margin-bottom:var(--sp-5)">
            <h3>Where it came from</h3>
            <p class="note" style="margin-bottom:var(--sp-4)">
              ${target.requires_source
                ? 'A citation is required for this kind of record. Without one it lands in “needs verification” rather than the approval queue.'
                : 'Optional here, but a citation is what lets anyone check this later.'}</p>
            <div id="sourceList"></div>
            <button type="button" class="btn-ghost btn-sm" id="addSource">+ Another source</button>
          </div>
          <div class="card">
            <h3>How to treat it</h3>
            <div class="field">
              <label for="visibility">Who may see this</label>
              <select id="visibility">
                <option value="public">Public — may appear on the site</option>
                <option value="internal">Internal — staff only, never published</option>
                <option value="confidential">Confidential — admins and editors only</option>
              </select>
              <div class="hint">The database refuses to publish anything that is not public,
                so this cannot leak by accident.</div>
            </div>
            <div class="field">
              <label for="confidence">How sure are you</label>
              <select id="confidence">
                <option value="high">High — read off the primary document</option>
                <option value="medium" selected>Medium — reported by a reliable publisher</option>
                <option value="low">Low — needs a second look</option>
                <option value="confirmed">Confirmed — verified against the filing</option>
              </select>
            </div>
            <div class="field">
              <label for="rationale">Note for the reviewer</label>
              <textarea id="rationale" placeholder="What makes this worth adding, and anything the reviewer should check."></textarea>
            </div>
            <button class="btn-primary" style="width:100%" type="submit">Send to review queue</button>
          </div>
        </div>
      </form>`;

    addSourceRow();
    $('#addSource').addEventListener('click', () => addSourceRow());
    $('#view').querySelectorAll('.picker').forEach(wirePicker);
    $('#addForm').addEventListener('submit', (e) => submitAdd(e, target, existing));
  }

  function addSourceRow() {
    const n = $('#sourceList').children.length + 1;
    $('#sourceList').appendChild(el(`
      <div class="field" style="border:1px solid var(--line);border-radius:var(--radius);padding:var(--sp-4)">
        <div class="kicker" style="margin-bottom:var(--sp-3)">Source ${n}</div>
        <div class="field">
          <label>Already in the source registry?</label>
          <div class="picker" data-kind="srcref" data-lookup="source" data-value="">
            <input type="search" placeholder="Search publishers and titles…" autocomplete="off">
          </div>
        </div>
        <div class="note" style="margin:-6px 0 10px">or describe a new one:</div>
        <div class="field"><label>URL</label><input data-src="url" type="url" placeholder="https://"></div>
        <div class="field"><label>Publisher</label><input data-src="publisher" placeholder="QSR Magazine"></div>
        <div class="field"><label>Title</label><input data-src="title"></div>
        <div class="field"><label>As of</label><input data-src="date_label" placeholder="Q3 2026, FY2025, Aug 2026"></div>
        <div class="field" style="margin-bottom:0"><label>The sentence it came from</label>
          <textarea data-src="quote" placeholder="Paste the line that states the figure. This is what makes checking it a minute rather than an afternoon."></textarea></div>
      </div>`));
    $('#sourceList').querySelectorAll('.picker').forEach(wirePicker);
  }

  /* Typeahead against review_lookup. What it stores is a token — @brand:popeyes — not a
     uuid, so the proposal stays readable in the diff and resolves at approval time. */
  /* For the polymorphic picker, both the table to search and the token prefix are
     decided by the subject_type select rather than by a foreign key. */
  const subjectKind = () => {
    const sel = document.querySelector('[data-col="subject_type"]');
    return (sel && sel.value) || 'brand';
  };

  function wirePicker(p) {
    if (p.dataset.wired) return;
    p.dataset.wired = '1';
    const input = p.querySelector('input');
    let timer;
    const kindOf = () => (p.dataset.lookup === 'subject' ? subjectKind() : p.dataset.lookup);
    const tokenOf = () => (p.dataset.token === 'auto' ? '@' + subjectKind() : p.dataset.token);
    const pick = (r) => {
      const token = tokenOf();
      p.dataset.value = token ? `${token}:${r.ref}` : r.ref;
      p.dataset.ref = r.ref;
      const keep = { lookup: p.dataset.lookup, token: p.dataset.token, col: p.dataset.col,
                     kind: p.dataset.kind };
      p.innerHTML = `<div class="picked"><span>${h(r.label)}</span>
        <span class="note mono">${h(r.ref)}</span>
        <button type="button" class="x" aria-label="Clear">✕</button></div>`;
      p.querySelector('.x').addEventListener('click', () => {
        p.dataset.value = ''; p.dataset.ref = ''; p.dataset.wired = '';
        Object.assign(p.dataset, keep);
        p.innerHTML = `<input type="search" placeholder="Search…" autocomplete="off">`;
        wirePicker(p);
      });
    };
    input.addEventListener('input', () => {
      clearTimeout(timer);
      const q = input.value.trim();
      const old = p.querySelector('.results'); if (old) old.remove();
      if (q.length < 2) return;
      timer = setTimeout(async () => {
        try {
          const kind = kindOf();
          if (kind === 'category') {
            input.value = ''; p.dataset.value = ''; return;
          }
          const { results } = await api('lookup', { kind, q });
          const box = el(`<div class="results">${
            results.length ? results.map((r, i) =>
              `<button type="button" data-i="${i}"><div>${h(r.label)}</div>
               <div class="d">${h(r.ref)}${r.detail ? ' · ' + h(r.detail) : ''}</div></button>`).join('')
            : '<button type="button" disabled>Nothing matches — describe it as new below.</button>'}</div>`);
          p.appendChild(box);
          box.querySelectorAll('[data-i]').forEach((b) =>
            b.addEventListener('click', () => pick(results[Number(b.dataset.i)])));
        } catch (e) { /* a failed lookup must not block typing */ }
      }, 220);
    });
    document.addEventListener('click', (e) => {
      if (!p.contains(e.target)) { const r = p.querySelector('.results'); if (r) r.remove(); }
    });
  }

  async function submitAdd(e, target, existing) {
    e.preventDefault();
    const btn = $('#addForm button[type=submit]');
    btn.disabled = true; btn.textContent = 'Sending…';

    const payload = {};
    $('#addForm').querySelectorAll('[data-col]').forEach((f) => {
      const col = f.dataset.col; const kind = f.dataset.kind;
      let v;
      if (kind === 'ref') v = f.dataset.value || '';
      else if (kind === 'bool') v = f.checked;
      else v = f.value;
      if (kind === 'bool') { payload[col] = v; return; }
      if (v === '' || v == null) return;
      if (kind === 'num') { const n = Number(v); if (!isNaN(n)) payload[col] = n; return; }
      if (kind === 'array') { payload[col] = String(v).split(',').map((s) => s.trim()).filter(Boolean); return; }
      if (kind === 'json') { try { payload[col] = JSON.parse(v); } catch { toast(`${col} is not valid JSON`, true); } return; }
      payload[col] = v;
    });

    const sources = [];
    $('#sourceList').querySelectorAll(':scope > div').forEach((row) => {
      const picker = row.querySelector('.picker');
      const src = {};
      row.querySelectorAll('[data-src]').forEach((f) => { if (f.value.trim()) src[f.dataset.src] = f.value.trim(); });
      if (picker && picker.dataset.ref) sources.push({ source_key: picker.dataset.ref, quote: src.quote });
      else if (src.url) sources.push(src);
    });

    /* If a source was cited but no source_id was filled in on the record itself, point
       the record at the first citation. Forgetting this is the single most common way a
       figure ends up on the site with no footnote. */
    const hasSourceCol = target.columns.some((c) => c.name === 'source_id');
    if (hasSourceCol && !payload.source_id && sources.length) payload.source_id = '@source:1';

    const entity = payload.name || payload.title || payload.headline || existing && existing.label;
    const item = {
      target_table: target.table_name,
      operation: existing ? 'update' : 'insert',
      target_id: existing ? existing.id : undefined,
      title: `${existing ? 'Edit to' : 'New'} ${target.label.toLowerCase()}${entity ? `: ${entity}` : ''}`,
      entity_label: entity || undefined,
      rationale: $('#rationale').value.trim() || undefined,
      confidence: $('#confidence').value,
      visibility: $('#visibility').value,
      payload, sources
    };

    try {
      const { result } = await api('submit', { batch: { title: 'Desk entry' }, items: [item] });
      const r = (result.items || [])[0] || {};
      if (!r.accepted) throw new Error((r.errors || ['That could not be queued.']).join('; '));
      const problems = [].concat(r.errors || [], r.warnings || []);
      toast(problems.length ? `Queued, with notes: ${problems.join('; ')}` : 'Queued for review.');
      location.hash = `#/queue?status=all&id=${r.id}`;
    } catch (err) {
      toast(err.message, true);
      btn.disabled = false; btn.textContent = 'Send to review queue';
    }
  }

  /* ---------- research runs ---------- */
  views.runs = async (params) => {
    setHead('Research runs', 'A run is one task; its findings are reviewed one by one');
    if (params.get('id')) {
      const { batch, items } = await api('batch', { id: params.get('id') });
      const open = items.filter((i) => i.status === 'pending');
      $('#view').innerHTML = `
        <div class="row" style="margin-bottom:var(--sp-4)"><a class="btn btn-ghost btn-sm" href="#/runs">← All runs</a></div>
        <div class="card" style="margin-bottom:var(--sp-5)">
          <div class="row" style="gap:8px;margin-bottom:8px">
            <span class="tag ${batch.kind === 'agent' ? 'agent' : ''}">${h(batch.kind)}</span>
            <span class="tag">${h(batch.status)}</span>
            ${batch.model ? `<span class="tag">${h(batch.model)}</span>` : ''}
          </div>
          <h2>${h(batch.title)}</h2>
          <div class="note" style="margin-top:6px">${h(batch.agent_name || '')} · started ${h(ago(batch.started_at))}
            ${batch.finished_at ? ` · finished ${h(ago(batch.finished_at))}` : ''} · ${items.length} proposals</div>
          ${batch.task_prompt ? `<div class="section" style="margin-top:var(--sp-4)">
            <div class="kicker">What it was asked to do</div>
            <p class="note" style="margin:0">${h(batch.task_prompt)}</p></div>` : ''}
          ${batch.summary_md ? `<div class="section" style="margin-top:var(--sp-4)">
            <div class="kicker">What it reported</div>
            <p class="note" style="margin:0">${h(batch.summary_md)}</p></div>` : ''}
          ${open.length && state.me.can_edit ? `<div class="row" style="margin-top:var(--sp-5)">
            <button class="btn-primary" id="approveAll">Approve all ${open.length} remaining</button>
            <span class="note">Each one is still checked and applied individually.</span>
          </div>` : ''}
        </div>
        <div class="list">${items.map((i) => queueRow(i)).join('')}</div>`;
      $('#view').querySelectorAll('.item').forEach((b) =>
        b.addEventListener('click', () => { location.hash = `#/queue?status=all&id=${b.dataset.id}`; }));
      const all = $('#approveAll');
      if (all) all.addEventListener('click', async () => {
        if (!confirm(`Approve ${open.length} proposals from this run?`)) return;
        all.disabled = true; all.textContent = 'Approving…';
        const { done, failed } = await api('decideMany',
          { ids: open.map((i) => i.id), decision: 'approve' });
        toast(`${done.length} approved${failed.length ? `, ${failed.length} could not be` : ''}.`,
              failed.length > 0);
        views.runs(params);
      });
      return;
    }

    const { batches } = await api('batches', {});
    $('#view').innerHTML = batches.length ? `<div class="list">${batches.map((b) => `
      <button class="item" data-id="${h(b.id)}">
        <div class="t">${h(b.title)}</div>
        <div class="m">
          <span class="tag ${b.kind === 'agent' ? 'agent' : ''}">${h(b.kind)}</span>
          ${b.agent_name ? `<span>${h(b.agent_name)}</span><span class="dot">·</span>` : ''}
          <span>${(b.items && b.items[0] ? b.items[0].count : 0)} proposals</span>
          <span class="dot">·</span><span>${h(ago(b.started_at))}</span>
          ${b.status === 'open' ? '<span class="tag pending">still running</span>' : ''}
        </div></button>`).join('')}</div>`
      : `<div class="empty"><b>No runs yet</b>A research run appears here the moment an agent
         submits its first finding. Mint a key under Settings to start one.</div>`;
    $('#view').querySelectorAll('.item').forEach((b) =>
      b.addEventListener('click', () => { location.hash = `#/runs?id=${b.dataset.id}`; }));
  };

  /* ---------- canonical data ---------- */
  views.data = async (params) => {
    if (!state.targets) state.targets = (await api('schema')).targets;
    const table = params.get('table') || 'public.transactions';
    const target = state.targets.find((t) => t.table_name === table) || state.targets[0];
    setHead('Intelligence', 'What the database holds, published and held back');

    const { records } = await api('records', { table: target.table_name, q: params.get('q') || undefined });
    $('#view').innerHTML = `
      <div class="row" style="margin-bottom:var(--sp-4)">
        <select id="tableSel" style="max-width:280px">
          ${state.targets.map((t) => `<option value="${h(t.table_name)}" ${t.table_name === target.table_name ? 'selected' : ''}>
            ${h(t.plural_label)}</option>`).join('')}
        </select>
        <input id="dSearch" type="search" placeholder="Search" style="max-width:260px"
               value="${h(params.get('q') || '')}">
        <a class="btn btn-sm" href="#/add?table=${encodeURIComponent(target.table_name)}">+ New ${h(target.label.toLowerCase())}</a>
      </div>
      <div class="split">
        <div class="list">${records.length ? records.map((r) => `
          <button class="item" data-id="${h(r.id)}">
            <div class="t">${h(r.label || r.id)}</div>
            <div class="m">
              ${r.row.visibility && r.row.visibility !== 'public' ? visTag(r.row.visibility) : ''}
              ${r.row.is_published === false ? '<span class="tag">unpublished</span>' : ''}
              ${r.row.is_published === true ? '<span class="tag applied">on the site</span>' : ''}
              ${r.row.created_at ? `<span>${h(ago(r.row.created_at))}</span>` : ''}
            </div></button>`).join('')
          : `<div class="empty"><b>Nothing here</b>No ${h(target.plural_label.toLowerCase())} match.</div>`}
        </div>
        <div id="dDetail"></div>
      </div>`;

    $('#tableSel').addEventListener('change', (e) => {
      location.hash = `#/data?table=${encodeURIComponent(e.target.value)}`;
    });
    let t;
    $('#dSearch').addEventListener('input', (e) => {
      clearTimeout(t);
      const v = e.target.value;
      t = setTimeout(() => {
        location.hash = `#/data?table=${encodeURIComponent(target.table_name)}${v ? '&q=' + encodeURIComponent(v) : ''}`;
      }, 350);
    });
    $('#view').querySelectorAll('.item').forEach((b) => b.addEventListener('click', async () => {
      $('#view').querySelectorAll('.item').forEach((x) => x.classList.toggle('on', x === b));
      const rec = records.find((r) => r.id === b.dataset.id);
      const box = $('#dDetail');
      box.innerHTML = '<div class="card loading"><span class="spin"></span></div>';
      const { history } = await api('history', { table: target.table_name, id: rec.id }).catch(() => ({ history: [] }));
      box.innerHTML = `<div class="detail"><div class="head">
          <h2>${h(rec.label || rec.id)}</h2>
          <div class="note" style="margin-top:4px">${h(target.label)}</div>
        </div>
        <div class="body">
          <div class="section"><dl class="kv">${Object.entries(rec.row)
            .filter(([k, v]) => v !== null && v !== '' && k !== 'id')
            .map(([k, v]) => `<dt>${h(k)}</dt><dd>${h(show(v))}</dd>`).join('')}</dl></div>
          <div class="section">
            <div class="kicker">Change history</div>
            ${history.length ? `<dl class="kv">${history.map((e) => `
              <dt>${h(ago(e.changed_at))}</dt>
              <dd>${h(e.operation.toLowerCase())}${e.changed_by_name ? ` by ${h(e.changed_by_name)}` : ''}</dd>`).join('')}</dl>`
              : '<p class="note">No recorded changes since this record was created.</p>'}
          </div>
        </div>
        <div class="actions">
          <a class="btn btn-primary" href="#/add?table=${encodeURIComponent(target.table_name)}&id=${h(rec.id)}">
            Propose an edit</a>
        </div></div>`;
    }));
  };

  /* ---------- leads ---------- */
  views.leads = async (params) => {
    setHead('Leads', 'Everything the site\'s forms have collected');
    const status = params.get('status') || '';
    const { leads } = await api('leads', { status: status || undefined, limit: 100 });
    const chip = (v, l) => `<button class="chip ${status === v ? 'on' : ''}" data-s="${h(v)}">${h(l)}</button>`;
    $('#view').innerHTML = `
      <div class="chips" style="margin-bottom:var(--sp-4)">
        ${chip('', 'All')}${chip('new', 'New')}${chip('triaged', 'Triaged')}
        ${chip('qualified', 'Qualified')}${chip('spam', 'Spam')}
      </div>
      <div class="list">${leads.length ? leads.map((l) => `
        <div class="item" style="cursor:default">
          <div class="row" style="justify-content:space-between;align-items:flex-start">
            <div style="min-width:0">
              <div class="t">${h(l.full_name || l.email || 'Anonymous')} · ${h(l.form.replace(/_/g, ' '))}</div>
              <div class="m">
                <span class="tag ${l.status === 'new' ? 'pending' : ''}">${h(l.status)}</span>
                ${l.email ? `<span>${h(l.email)}</span>` : ''}
                ${l.phone ? `<span class="dot">·</span><span>${h(l.phone)}</span>` : ''}
                <span class="dot">·</span><span>${h(ago(l.created_at))}</span>
              </div>
            </div>
            ${state.me.can_edit ? `<select data-lead="${h(l.id)}" style="max-width:150px">
              ${['new', 'triaged', 'contacted', 'qualified', 'converted', 'spam', 'closed']
                .map((s) => `<option ${s === l.status ? 'selected' : ''}>${s}</option>`).join('')}
            </select>` : ''}
          </div>
          <pre class="json" style="margin-top:10px">${h(JSON.stringify(l.payload, null, 2))}</pre>
        </div>`).join('')
        : `<div class="empty"><b>No submissions yet</b>Anything sent through the site's five
           forms lands here, and in the intake schema.</div>`}</div>`;
    $('#view').querySelectorAll('.chip').forEach((c) => c.addEventListener('click', () => {
      location.hash = `#/leads${c.dataset.s ? '?status=' + c.dataset.s : ''}`;
    }));
    $('#view').querySelectorAll('[data-lead]').forEach((s) => s.addEventListener('change', async () => {
      try { await api('leadUpdate', { id: s.dataset.lead, status: s.value }); toast('Updated.'); }
      catch (e) { toast(e.message, true); }
    }));
  };

  /* ---------- settings ---------- */
  views.settings = async () => {
    setHead('Settings', 'Access, and the keys research agents use');
    const [{ keys }, { staff }] = await Promise.all([
      api('agentKeys').catch(() => ({ keys: [] })),
      api('staff').catch(() => ({ staff: [] }))
    ]);

    $('#view').innerHTML = `
      <div class="grid g2" style="align-items:start">
        <div class="card">
          <h3>Agent keys</h3>
          <p class="note" style="margin-bottom:var(--sp-4)">
            A key lets a research agent put findings in the review queue. It cannot read or
            write canonical data, cannot approve anything, and cannot see a lead. Give each
            agent its own so one can be revoked without stopping the others.</p>
          <div id="keyList">${keys.length ? keys.map((k) => `
            <div class="row" style="justify-content:space-between;border:1px solid var(--line);
                 border-radius:var(--radius);padding:10px 12px;margin-bottom:8px">
              <div><div style="font-weight:600;font-size:13.5px">${h(k.name)}
                ${k.revoked_at ? '<span class="tag rejected">revoked</span>' : ''}</div>
                <div class="note mono">${h(k.key_prefix)}… · ${h(k.scopes.join(', '))} ·
                  used ${k.use_count} time${k.use_count === 1 ? '' : 's'}${k.last_used_at ? ', last ' + h(ago(k.last_used_at)) : ''}</div></div>
              ${!k.revoked_at && state.me.can_edit
                ? `<button class="btn-danger btn-sm" data-revoke="${h(k.id)}">Revoke</button>` : ''}
            </div>`).join('') : '<p class="note">No keys yet.</p>'}</div>
          ${state.me.can_edit ? `<div class="row" style="margin-top:var(--sp-4)">
            <input id="keyName" placeholder="Claude research" style="max-width:220px">
            <button class="btn-primary" id="mintKey">Mint a key</button></div>` : ''}
          <div id="newKey"></div>
        </div>

        <div class="card">
          <h3>Desk access</h3>
          <p class="note" style="margin-bottom:var(--sp-4)">
            Roles: <b>admin</b> does everything; <b>editor</b> approves and edits;
            <b>analyst</b> proposes but cannot approve and cannot see confidential
            intelligence; <b>viewer</b> reads.</p>
          <dl class="kv" style="margin-bottom:var(--sp-4)">
            ${staff.map((s) => `<dt>${h(s.role)}</dt><dd>${h(s.email)}${s.full_name ? ` · ${h(s.full_name)}` : ''}</dd>`).join('')}
          </dl>
          ${state.me.is_admin ? `
            <div class="row">
              <input id="grantEmail" type="email" placeholder="them@example.com" style="max-width:200px">
              <select id="grantRole" style="max-width:120px">
                <option>editor</option><option>analyst</option><option>viewer</option><option>admin</option>
              </select>
              <button id="grantBtn">Grant</button>
            </div>
            <div class="hint">They must have signed in once first — an account is created in
              Supabase under Authentication → Users.</div>` : ''}
        </div>
      </div>

      <div class="card" style="margin-top:var(--sp-5)">
        <h3>How an agent submits research</h3>
        <p class="note">Any agent — a Claude Code session, a scheduled script — posts to
          <code>/api/agent</code> with its key. Everything it sends waits here for a decision.
          The full contract is in <code>db/AGENT_INTAKE.md</code>.</p>
        <pre class="json">curl -X POST ${h(location.origin)}/api/agent \\
  -H "Authorization: Bearer csw_ag_..." \\
  -H "Content-Type: application/json" \\
  -d '{
    "op": "submit",
    "batch": { "title": "Q3 chicken AUVs", "model": "claude-opus-5",
               "task_prompt": "Find published Q3 2026 AUVs for the tracked brands." },
    "items": [{
      "target_table": "public.facts",
      "title": "Popeyes AUV FY2026",
      "entity_label": "Popeyes",
      "confidence": "high",
      "rationale": "Stated in RBI'"'"'s Q4 release.",
      "payload": {
        "subject_type": "brand", "subject_id": "@brand:popeyes",
        "metric_key": "auv_usd", "value_numeric": 1810000,
        "unit": "usd", "period_label": "FY2026", "source_id": "@source:1"
      },
      "sources": [{ "publisher": "Restaurant Brands International",
                    "url": "https://example.com/q4", "date_label": "Q4 2026",
                    "quote": "U.S. average restaurant sales of $1.81 million" }]
    }]
  }'</pre>
      </div>`;

    const mint = $('#mintKey');
    if (mint) mint.addEventListener('click', async () => {
      mint.disabled = true;
      try {
        const { secret } = await api('agentKeyCreate', { name: $('#keyName').value.trim() });
        $('#newKey').innerHTML = `<div class="msg ok" style="margin-top:var(--sp-4)">
          <b>Copy this now — it is not stored and cannot be shown again</b>
          <div class="secret" style="margin-top:8px">${h(secret)}</div></div>`;
        views.settings();
      } catch (e) { toast(e.message, true); mint.disabled = false; }
    });
    $('#view').querySelectorAll('[data-revoke]').forEach((b) => b.addEventListener('click', async () => {
      if (!confirm('Revoke this key? Anything using it stops immediately.')) return;
      await api('agentKeyRevoke', { id: b.dataset.revoke });
      toast('Revoked.'); views.settings();
    }));
    const grant = $('#grantBtn');
    if (grant) grant.addEventListener('click', async () => {
      try {
        await api('grantStaff', { email: $('#grantEmail').value.trim(), role: $('#grantRole').value });
        toast('Access granted.'); views.settings();
      } catch (e) { toast(e.message, true); }
    });
  };

  /* ---------- router ---------- */
  async function route() {
    const raw = (location.hash || '#/overview').slice(2);
    const [name, query] = raw.split('?');
    const view = views[name] || views.overview;
    const params = new URLSearchParams(query || '');
    renderNav(views[name] ? name : 'overview');
    document.body.classList.remove('railopen');
    $('#view').innerHTML = '<div class="loading"><span class="spin"></span></div>';
    try {
      await view(params);
    } catch (e) {
      if (e.status === 403 || e.status === 401) return boot();
      $('#view').innerHTML = `<div class="msg err"><b>Could not load that</b>${h(e.message)}</div>`;
    }
  }

  /* Working a queue is repetitive, so it gets keys. Ignored while typing. */
  document.addEventListener('keydown', (e) => {
    if (/^(INPUT|TEXTAREA|SELECT)$/.test(document.activeElement.tagName)) return;
    if (e.metaKey || e.ctrlKey || e.altKey) return;
    const rows = [...document.querySelectorAll('#qList .item')];
    if (!rows.length) return;
    const i = rows.findIndex((r) => r.classList.contains('on'));
    if (e.key === 'j' || e.key === 'k') {
      e.preventDefault();
      const next = rows[Math.max(0, Math.min(rows.length - 1, i + (e.key === 'j' ? 1 : -1)))];
      if (next) { next.click(); next.scrollIntoView({ block: 'nearest' }); }
    }
    const act = { a: 'approve', r: 'reject', v: 'needs_verification' }[e.key];
    if (act) {
      const btn = document.querySelector(`#qDetail [data-act="${act}"]`);
      if (btn && !btn.disabled) { e.preventDefault(); btn.click(); }
    }
  });

  /* ---------- boot ---------- */
  async function boot() {
    /* An emailed magic link comes back with the tokens in the fragment. Consume them and
       clean the URL so a session never sits in the address bar or a shared screenshot. */
    if (location.hash.includes('access_token=')) {
      const p = new URLSearchParams(location.hash.slice(1));
      if (p.get('access_token')) {
        saveSession({ access_token: p.get('access_token'), refresh_token: p.get('refresh_token'),
                      expires_at: Date.now() + Number(p.get('expires_in') || 3600) * 1000 });
        history.replaceState(null, '', location.pathname + '#/overview');
      }
    }

    if (!state.cfg) {
      try { state.cfg = await (await fetch(API)).json(); }
      catch { state.cfg = { configured: false }; }
    }
    if (!state.session) state.session = loadSession();
    if (!state.session || !state.cfg.configured) return renderSignIn();

    let me;
    try { me = (await api('me')).me; }
    catch (e) {
      saveSession(null);
      return renderSignIn(e.status === 401 ? null
        : { kind: 'err', html: `<b>Could not reach the desk</b> ${h(e.message)}` });
    }
    state.me = me;
    if (!me.is_staff) return renderNoAccess(me);

    $('#signin').hidden = true;
    $('#app').hidden = false;
    $('#whoami').textContent = me.email;
    $('#whorole').textContent = me.role;
    try { state.stats = (await api('stats')).stats; } catch { /* the views retry */ }
    await route();
  }

  function start() {
    $('#signout').addEventListener('click', (e) => { e.preventDefault(); signOut(); });
    $('#railtoggle').addEventListener('click', () => document.body.classList.toggle('railopen'));
    window.addEventListener('hashchange', () => { if (state.me) route(); });
    boot();
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start);
  else start();
})();
