'use strict';
/**
 * data/*.json  ->  a single idempotent SQL seed.
 *
 *   node scripts/db-import.js > supabase/seed.sql
 *
 * Emits SQL rather than calling an API, for three reasons: it needs no credentials, so
 * nobody has to hand a service-role key to a script or paste one into a chat; it can be
 * applied through the Supabase SQL Editor exactly like the schema; and it is reviewable
 * as a diff before it touches anything.
 *
 * Ids are UUIDv5 derived from natural keys, so re-running produces identical rows and
 * `on conflict do nothing` makes the whole file safe to apply repeatedly.
 */
const fs = require('fs');
const path = require('path');
const { id, q, qn, qb, qa, insert, parsePeriod } = require('./lib/csw-db');

const D = (f) => JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'data', f), 'utf8'));
const data = {
  brands: D('brands.json'), operators: D('operators.json'), news: D('news.json'),
  transactions: D('transactions.json'), realestate: D('realestate.json'),
  expansion: D('expansion.json'), movement: D('movement.json'), markets: D('markets.json'),
  research: D('research.json'), datacenter: D('datacenter.json'),
  consumer: D('consumer.json'), events: D('events.json')
};
const sources = D('sources.json');

const out = [];
const say = (s) => out.push(s);
const section = (t) => say(`\n-- ${'='.repeat(74)}\n-- ${t}\n-- ${'='.repeat(74)}\n`);

const SRC = (k) => (k && sources[k] ? id('source', k) : null);
const srcq = (k) => (SRC(k) ? q(SRC(k)) : 'null');
const warn = [];

/* Everything the site labels "chicken brand". Non-chicken brands come from operators. */
const brandId = (slug) => id('brand', slug);
const coId    = (slug) => id('company', slug);
const slugify = (s) => String(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

say(`-- Generated by scripts/db-import.js. Do not edit.
-- Source of truth is data/*.json until Phase 4 flips the direction.
-- Safe to re-run: every insert is on-conflict-do-nothing over deterministic ids.

begin;`);

/* ---------------------------------------------------------------- sources */
section('sources');
say(insert('public.sources',
  ['id','key','publisher','title','url','date_label','published_on','source_type'],
  Object.entries(sources).map(([k, s]) => {
    const p = parsePeriod(s.date);
    const type = /sec\.gov|EDGAR/i.test(s.url + s.pub) ? 'sec_filing'
      : /Boulder Group|TopNetLease|Bull Realty|CoStar/i.test(s.pub) ? 'brokerage_report'
      : /USDA|Census/i.test(s.pub) ? 'government'
      : /FDD/i.test(s.title) ? 'fdd' : 'trade_press';
    return [q(id('source', k)), q(k), q(s.pub), q(s.title), q(s.url), q(s.date),
            p.start ? q(p.start) : 'null', q(type)];
  }), '(key)'));

/* ------------------------------------------------------------- categories */
section('category subject — the anchor for industry-level figures');
say(`insert into public.markets (id, slug, name, is_published) values
  (${q(id('category','us-chicken'))}, 'us-chicken-category', 'U.S. chicken restaurant category', false)
on conflict (slug) do nothing;`);

/* ---------------------------------------------------------------- brands */
section('brands');
const OWN = {
  'Private':'private','Public':'public','Public parent':'public_parent',
  'Private equity owned':'pe_owned','Private equity controlled':'pe_controlled',
  'Private, international parent':'private_intl_parent','Restructured':'restructured'
};
say(insert('public.brands',
  ['id','slug','name','is_chicken','sector','hq_label','founded_year','parent_label',
   'ownership_type','ownership_label','franchise_model_md','momentum','analysis_md','is_published'],
  data.brands.map((b) => {
    const [city, st] = String(b.hq || '').split(',').map((s) => s && s.trim());
    return [q(brandId(b.slug)), q(b.slug), q(b.name), 'true', `'restaurant'`, q(b.hq),
      qn(b.founded), q(b.parent),
      OWN[b.ownership] ? q(OWN[b.ownership]) : (b.ownership && /founder/i.test(b.ownership) ? `'family_controlled'` : 'null'),
      q(b.ownership), q(b.franchiseModel), q(b.momentum), q(b.analysis), 'true'];
  }), '(slug)'));

say('\n' + insert('public.brand_tags', ['brand_id','tag_key'],
  data.brands.flatMap((b) => (b.tags || []).map((t) => [q(brandId(b.slug)), q(t)])),
  '(brand_id, tag_key)'));

/* ------------------------------------------------------------- companies */
section('companies (operators) and the non-chicken brands they run');
const STATUS = {
  'Acquiring':'acquiring','Liquidated (Chapter 11)':'liquidated','Newly formed':'newly_formed',
  'Refranchising candidate':'refranchising','Actively developing':'active',
  'Acquired by Eyas Capital':'acquired','Stable / diversifying':'stable','Divesting':'divesting'
};
say(insert('public.companies',
  ['id','slug','name','hq_label','kind','status','status_note','geography','analysis_md','is_published'],
  data.operators.map((o) => [q(coId(o.slug)), q(o.slug), q(o.name), q(o.hq), `'operator'`,
    STATUS[o.status] ? q(STATUS[o.status]) : 'null', q(o.status), qa(o.geography),
    q(o.analysis), 'true']), '(slug)'));

say('\n' + insert('public.company_roles', ['company_id','role'],
  data.operators.map((o) => [q(coId(o.slug)), `'operator'`]), '(company_id, role)'));

/* Non-chicken brands become real rows so brand_operators can be a foreign key. Two of
   them are not restaurants at all: Meineke and Take 5 Oil Change. */
const SECTOR = { 'meineke':'automotive','take-5-oil-change':'automotive','7-eleven':'convenience' };
const chickenNames = new Set(data.brands.map((b) => b.name.toLowerCase()));
const others = new Map();
for (const o of data.operators) {
  for (const bn of o.brands || []) {
    if (chickenNames.has(bn.toLowerCase())) continue;
    const s = slugify(bn);
    if (!others.has(s)) others.set(s, bn);
  }
}
say(insert('public.brands', ['id','slug','name','is_chicken','sector','is_published'],
  [...others].map(([s, n]) => [q(brandId(s)), q(s), q(n), 'false',
    q(SECTOR[s] || 'restaurant'), 'false']), '(slug)'));

/* brand_operators: the foreign key replacing build.js fuzzy string matching. */
const resolveBrand = (name) => {
  const lower = name.toLowerCase();
  const hit = data.brands.find((x) => x.name.toLowerCase() === lower)
    || data.brands.find((x) => x.name.toLowerCase().includes(lower) || lower.includes(x.name.split(' ')[0].toLowerCase()));
  if (hit) return hit.slug;
  const s = slugify(name);
  return others.has(s) ? s : null;
};
const bo = [];
for (const o of data.operators) {
  for (const bn of o.brands || []) {
    const s = resolveBrand(bn);
    if (!s) { warn.push(`brand_operators: could not resolve "${bn}" for ${o.slug}`); continue; }
    const isChicken = (o.chickenBrands || []).some((c) => c.toLowerCase() === bn.toLowerCase());
    bo.push([q(id('bo', `${o.slug}:${s}`)), q(brandId(s)), q(coId(o.slug)),
             isChicken && o.chickenUnits != null ? qn(o.chickenUnits) : 'null', 'true']);
  }
}
say('\n' + insert('public.brand_operators', ['id','brand_id','company_id','unit_count','is_current'], bo));

/* ---------------------------------------------------------------- markets */
section('markets');
say(insert('public.markets', ['id','slug','name','state','thesis_md','is_published'],
  data.markets.map((m) => [q(id('market', m.slug)), q(m.slug), q(m.name), q(m.state),
    q(m.thesis), 'true']), '(slug)'));

/* ----------------------------------------------------------------- facts */
section('facts — every published figure, individually sourced');
const snake = (k) => k.replace(/([a-z])([A-Z])/g,'$1_$2').replace(/([A-Z]+)([A-Z][a-z])/g,'$1_$2')
                      .replace(/([a-zA-Z])(\d)/g,'$1_$2').toLowerCase();
const factRows = [];
const pushFact = (kind, subj, metric, value, unit, period, src, opts = {}) => {
  if (src == null) { warn.push(`fact ${metric} on ${kind} has no source — skipped`); return; }
  const p = parsePeriod(period);
  factRows.push([q(id('fact', `${kind}:${subj}:${metric}:${period}`)), q(kind), q(subj), q(metric),
    qn(value), 'null', q(unit), q(period), p.start ? q(p.start) : 'null', p.end ? q(p.end) : 'null',
    'null', q(src), q(opts.derivation || 'reported'), q(opts.note)]);
};

for (const b of data.brands) {
  for (const [k, st] of Object.entries(b.stats || {})) {
    const unit = st.fmt === 'usd' ? 'usd' : st.fmt === 'pct' ? 'pct' : 'count';
    pushFact('brand', brandId(b.slug), snake(k), st.v, unit, st.asOf, SRC(st.src), { note: st.note });
  }
  /* Derived numerics that feed the score. They carry no src of their own, so each
     inherits the source of the published figure it is computed from. */
  const m = b.metrics || {};
  const stat = (...names) => names.map((n) => b.stats && b.stats[n]).find(Boolean);
  const fallback = Object.values(b.stats || {})[0];
  const pick = (s) => SRC((s || fallback || {}).src);
  const period = (s) => ((s || fallback || {}).asOf) || 'latest';
  const map = [
    ['auv_usd', m.auvUsd, 'usd', stat('auv','blendedAuv'), m.auvNote, false],
    ['unit_growth_pct', m.unitGrowthPct, 'pct', stat('usUnits','globalUnits','usCanadaUnits','currentUnits'), null, m.unitGrowthDerived],
    ['sales_growth_pct', m.salesGrowthPct, 'pct', stat('systemwideSales','globalSales'), m.salesGrowthNote, m.salesGrowthDerived],
    ['comps_pct', m.compsPct, 'pct', stat('compsLatest','compsFY'), null, false],
    ['cap_rate_mid', m.capRateMid, 'pct', null, m.capRateBasis, false]
  ];
  for (const [key, val, unit, s, note, derived] of map) {
    if (val == null) continue;
    const src = key === 'cap_rate_mid'
      ? SRC((b.realEstate && b.realEstate.capSrc && b.realEstate.capSrc[0]) || (fallback || {}).src)
      : pick(s);
    pushFact('brand', brandId(b.slug), key, val, unit, period(s), src,
      { derivation: derived ? 'derived' : 'reported', note });
  }
  if (m.netClosures != null)
    pushFact('brand', brandId(b.slug), 'net_unit_decline', m.netClosures ? 1 : 0, 'ratio',
      period(fallback), pick(fallback), { derivation: 'derived' });
}

for (const o of data.operators) {
  const src = SRC(((o.facts || [])[0] || {}).src);
  if (o.chickenUnits != null)
    pushFact('company', coId(o.slug), 'operator_chicken_units', o.chickenUnits, 'count',
      ((o.facts || [])[0] || {}).asOf || 'latest', src, { note: o.chickenUnitsNote });
  if (o.totalUnits != null)
    pushFact('company', coId(o.slug), 'operator_total_units', o.totalUnits, 'count',
      ((o.facts || [])[0] || {}).asOf || 'latest', src);
}

const BENCH = { 'Corporate-guaranteed QSR':'cap_rate_corporate_qsr',
  'Franchisee-guaranteed QSR':'cap_rate_franchisee_qsr',
  'All single-tenant net lease':'cap_rate_all_net_lease',
  'Single-tenant retail':'cap_rate_single_tenant_retail',
  "Premium QSR ground lease (McDonald's / Chick-fil-A)":'cap_rate_premium_ground_lease' };
for (const bm of data.realestate.benchmarks) {
  const key = BENCH[bm.label];
  if (!key) { warn.push(`benchmark "${bm.label}" has no metric key`); continue; }
  const cat = id('category', 'us-chicken');
  const p = parsePeriod(bm.asOf);
  factRows.push([q(id('fact', `category:${cat}:${key}:${bm.asOf}`)), `'category'`, q(cat), q(key),
    qn(parseFloat(bm.value)), 'null', `'pct'`, q(bm.asOf), p.start ? q(p.start) : 'null',
    p.end ? q(p.end) : 'null', 'null', srcq(bm.src), `'reported'`, q(bm.change)]);
}
say(insert('public.facts',
  ['id','subject_type','subject_id','metric_key','value_numeric','value_text','unit',
   'period_label','period_start','period_end','as_of','source_id','derivation','note'], factRows));

/* ---------------------------------------------------------- cap rates */
section('brand cap rates');
const capRows = [], capSrcRows = [];
for (const b of data.brands) {
  const re = b.realEstate; if (!re || !re.capRate) continue;
  const cid = id('caprate', `brand-page:${b.slug}`);
  capRows.push([q(cid), q(brandId(b.slug)), qn((b.metrics || {}).capRateMid), q(re.capRate),
    'null', q((b.metrics || {}).capRateBasis || 'brand page'), srcq((re.capSrc || [])[0]), 'null']);
  (re.capSrc || []).forEach((s, i) => capSrcRows.push([q(cid), srcq(s), String(i)]));
}
data.realestate.brandCapRates.forEach((c, i) => {
  /* Two of these are not brands: a McDonald's reference row and a franchisee-QSR
     aggregate, both with slug: null. They keep their label and no brand_id. */
  const cid = id('caprate', `desk:${c.slug || 'ref-' + i}`);
  capRows.push([q(cid), c.slug ? q(brandId(c.slug)) : 'null', 'null', q(c.range),
    q(c.structure), 'null', srcq(c.src), q(c.brand)]);
  capSrcRows.push([q(cid), srcq(c.src), '0']);
});
say(insert('public.brand_cap_rates',
  ['id','brand_id','mid_pct','range_label','structure','basis','source_id','brand_label'], capRows));
say('\n' + insert('public.cap_rate_sources', ['cap_rate_id','source_id','ordinal'], capSrcRows,
  '(cap_rate_id, source_id)'));

/* ------------------------------------------------------------ entity notes */
section('entity notes — the sourced-bullet pattern, six arrays unified');
const noteRows = [], noteSrcRows = [];
const pushNote = (key, kind, subjKind, subjId, body, srcs, o = {}) => {
  const nid = id('note', key);
  noteRows.push([q(nid), q(subjKind), q(subjId), q(kind), q(o.label), q(body),
    q(o.period), srcq(srcs[0]), String(o.ordinal || 0)]);
  srcs.filter(Boolean).forEach((s, i) => noteSrcRows.push([q(nid), srcq(s), String(i)]));
};
data.brands.forEach((b) => {
  (b.pipeline || []).forEach((p, i) =>
    pushNote(`pipeline:${b.slug}:${i}`, 'pipeline', 'brand', brandId(b.slug), p.text, [p.src], { ordinal: i }));
  if (b.realEstate && b.realEstate.notes)
    pushNote(`re-note:${b.slug}`, 'real_estate_note', 'brand', brandId(b.slug),
      b.realEstate.notes, b.realEstate.notesSrc || []);
});
data.operators.forEach((o) => (o.facts || []).forEach((f, i) =>
  pushNote(`opfact:${o.slug}:${i}`, 'operator_fact', 'company', coId(o.slug), f.text, [f.src],
    { period: f.asOf, ordinal: i })));
data.markets.forEach((m) => {
  (m.activity || []).forEach((a, i) =>
    pushNote(`mkt-act:${m.slug}:${i}`, 'market_activity', 'market', id('market', m.slug), a.text, [a.src], { ordinal: i }));
  (m.watch || []).forEach((w, i) =>
    pushNote(`mkt-watch:${m.slug}:${i}`, 'market_watch', 'market', id('market', m.slug), w, [], { ordinal: i }));
});
const cat = id('category', 'us-chicken');
data.realestate.leaseIntel.forEach((x, i) =>
  pushNote(`lease:${i}`, 'lease_intel', 'category', cat, x.text, [x.src], { label: x.label, ordinal: i }));
data.realestate.supply.forEach((x, i) =>
  pushNote(`supply:${i}`, 'supply', 'category', cat, x.text, [x.src], { label: x.label, ordinal: i }));
data.realestate.marketConditions.forEach((x, i) =>
  pushNote(`mktcond:${i}`, 'real_estate_note', 'category', cat, x.text, [x.src], { ordinal: i }));
data.consumer.context.forEach((x, i) =>
  pushNote(`ctx:${i}`, 'consumer_context', 'category', cat, x.text, [x.src], { ordinal: i }));
say(insert('public.entity_notes',
  ['id','subject_type','subject_id','kind','label','body_md','period_label','source_id','ordinal'], noteRows));
say('\n' + insert('public.note_sources', ['note_id','source_id','ordinal'], noteSrcRows, '(note_id, source_id)'));

/* --------------------------------------------------- properties & movement */
section('properties, occupancies and the system movement feed');
const AGG = /^(United States|National|Global|Eight U\.S\. markets|.*markets in one day)/i;
const propRows = [], occRows = [], moveRows = [];
const movement = [...data.movement.openings.map((m, i) => ({ ...m, dir: 'opening', i })),
                  ...data.movement.closures.map((m, i) => ({ ...m, dir: 'closure', i }))];
for (const ev of movement) {
  const key = `${ev.dir}:${ev.i}`;
  const isAggregate = ev.count != null || AGG.test(ev.location || '');
  let pid = null;
  if (!isAggregate) {
    pid = id('property', `${ev.brand}:${ev.location}`);
    const parts = String(ev.location).split(',').map((s) => s.trim());
    const st = parts.length > 1 ? parts[parts.length - 1] : null;
    propRows.push([q(pid), 'null', q(parts.length > 1 ? parts[parts.length - 2] : parts[0]),
      q(st && st.length <= 2 ? st : null), q(ev.location), `'operating'`, `'editorial'`,
      `'verified'`, 'true', srcq(ev.src)]);
    occRows.push([q(id('occ', key)), q(pid), q(brandId(ev.brand)),
      ev.dir === 'opening' ? `'open'` : `'closed'`,
      ev.dir === 'opening' ? q(parsePeriod(ev.date).start) : 'null',
      ev.dir === 'closure' ? q(parsePeriod(ev.date).start) : 'null',
      q(ev.detail), q(ev.date), srcq(ev.src)]);
  }
  const p = parsePeriod(ev.date);
  moveRows.push([q(id('move', key)), q(brandId(ev.brand)), q(ev.dir), q(ev.date),
    p.start && p.start === p.end ? q(p.start) : 'null', p.start ? q(p.start) : 'null',
    p.end ? q(p.end) : 'null', qn(ev.count), q(ev.location), q(ev.detail),
    pid ? q(pid) : 'null', srcq(ev.src), String(ev.i)]);
}
say(insert('public.properties',
  ['id','address_line1','city','state','location_label','status','record_source',
   'verification','is_published','source_id'], propRows));
say('\n' + insert('public.property_occupancies',
  ['id','property_id','brand_id','status','opened_on','closed_on','detail_md','date_label','source_id'], occRows));
say('\n' + insert('public.system_movements',
  ['id','brand_id','direction','date_label','occurred_on','period_start','period_end',
   'unit_count','location_label','detail_md','property_id','source_id','ordinal'], moveRows));

/* ----------------------------------------------------------- transactions */
section('transactions, the properties they convey, and listings');
const TXK = { 'Property sale':'property_sale','Portfolio acquisition':'portfolio_acquisition',
  'Listing':'listing','Brand acquisition':'brand_acquisition','Franchisee portfolio':'franchisee_portfolio',
  'Bankruptcy sale':'bankruptcy_sale','Chapter 11 / company-store sale':'company_store_sale',
  'Growth investment':'growth_investment' };
const txRows = [], txPropRows = [], listRows = [], listPropRows = [];
data.transactions.property.forEach((t, i) => {
  const bslug = (data.brands.find((b) => t.brand.toLowerCase().includes(b.name.split(' ')[0].toLowerCase())) || {}).slug;
  if (t.type === 'Listing') {
    const lid = id('listing', `tx:${i}`);
    listRows.push([q(lid), q(`${t.brand} — ${t.location}`), q(t.detail), `'active'`,
      qn(t.price), qn(t.capRate), 'true', srcq(t.src), q(t.date), q(t.location), q(t.term),
      bslug ? q(brandId(bslug)) : 'null']);
    return;
  }
  const tid = id('tx', `property:${i}`);
  const specific = t.location && !/not disclosed/i.test(t.location) && /,/.test(t.location);
  txRows.push([q(tid), q(TXK[t.type] || 'property_sale'), `'property'`, q(t.date),
    q(parsePeriod(t.date).start), qn(t.price), qb(t.price != null), qn(t.capRate), 'null',
    'null', bslug ? q(brandId(bslug)) : 'null', q(t.location), q(t.term), q(t.detail),
    srcq(t.src), 'true', 'null', 'null']);
  if (specific) {
    const pid = id('property', `tx:${t.brand}:${t.location}`);
    propRows.push([q(pid), 'null', q(String(t.location).split(',').slice(-2, -1)[0] || t.location),
      'null', q(t.location), `'sold'`, `'editorial'`, `'verified'`, 'true', srcq(t.src)]);
    txPropRows.push([q(tid), q(pid)]);
  }
});
data.transactions.corporate.forEach((t, i) => {
  const tid = id('tx', `corporate:${i}`);
  const target = data.operators.find((o) => o.name === t.target)
    || data.brands.find((b) => b.name === t.target);
  const isBrand = target && data.brands.includes(target);
  txRows.push([q(tid), q(TXK[t.type] || 'brand_acquisition'), `'company'`, q(t.date),
    q(parsePeriod(t.date).start), qn(t.value), qb(t.value != null), 'null', 'null',
    (target && !isBrand) ? q(coId(target.slug)) : 'null', isBrand ? q(brandId(target.slug)) : 'null',
    'null', 'null', q(t.detail), srcq(t.src), 'true', q(t.target), q(t.acquirer)]);
});
/* Emit the extra properties discovered above alongside the originals. */
say(insert('public.properties',
  ['id','address_line1','city','state','location_label','status','record_source',
   'verification','is_published','source_id'], propRows.slice(occRows.length)));
say('\n' + insert('public.transactions',
  ['id','kind','subject','date_label','closed_on','price_usd','is_price_disclosed','cap_rate_pct',
   'noi_usd','buyer_company_id','brand_id','location_label','term_label','detail_md','source_id',
   'is_published','target_label','acquirer_label'], txRows));
say('\n' + insert('public.transaction_properties', ['transaction_id','property_id'], txPropRows,
  '(transaction_id, property_id)'));
say('\n' + insert('public.listings',
  ['id','headline','summary_md','status','asking_price_usd','cap_rate_pct','authorization_on_file',
   'source_id','date_label','location_label','term_label','brand_id'], listRows));

/* ------------------------------------------------------------- expansion */
section('expansion agreements');
say(insert('public.expansion_agreements',
  ['id','brand_id','operator_company_id','operator_label','market_label','unit_count','units_label',
   'announced_on','announced_label','timeline_note','source_id'],
  data.expansion.map((e, i) => {
    /* The field is mixed: some values are operator slugs, some are descriptions
       ('Company', 'Multiple franchisees'). Resolve what resolves, keep the label always. */
    const op = e.operator
      ? data.operators.find((o) => o.slug === e.operator) || data.operators.find((o) => o.name === e.operator)
      : null;
    return [q(id('exp', String(i))), q(brandId(e.brand)), op ? q(coId(op.slug)) : 'null',
      q(e.operator), q(e.market), qn(e.units), q(e.unitsLabel), q(parsePeriod(e.announced).start),
      q(e.announced), q(e.timeline), srcq(e.src)];
  })));

/* -------------------------------------------------------------- articles */
section('articles — news and research');
const artRows = [], artEnt = [], artSrc = [];
data.news.forEach((n, i) => {
  const aid = id('article', `news:${i}`);
  artRows.push([q(aid), q(`news-${i}-${slugify(n.title).slice(0, 60)}`), `'news'`, q(n.cat),
    q(n.title), 'null', 'null', q(n.means), 'null', q(n.date),
    q(parsePeriod(n.date).start), `'published'`, srcq(n.src), String(i)]);
  if (n.brand) artEnt.push([q(aid), `'brand'`, q(brandId(n.brand)), `'about'`]);
  artSrc.push([q(aid), srcq(n.src), '0']);
});
data.research.forEach((r, i) => {
  const aid = id('article', `research:${r.slug}`);
  artRows.push([q(aid), q(r.slug), `'research'`, 'null', q(r.title), q(r.dek),
    q(JSON.stringify(r.sections)), 'null', qn(parseInt(r.readTime, 10)), q(r.date),
    'null', `'published'`, 'null', String(i)]);
  const seen = new Set();
  r.sections.forEach((s) => (s.srcs || []).forEach((k) => {
    if (seen.has(k)) return; seen.add(k);
    artSrc.push([q(aid), srcq(k), String(seen.size - 1)]);
  }));
});
say(insert('public.articles',
  ['id','slug','kind','category','title','dek','body','means_md','read_minutes','date_label',
   'published_at','status','primary_source_id','sort_index'], artRows, '(slug)'));
say('\n' + insert('public.article_entities', ['article_id','subject_type','subject_id','relation'],
  artEnt, '(article_id, subject_type, subject_id)'));
say('\n' + insert('public.article_sources', ['article_id','source_id','ordinal'], artSrc,
  '(article_id, source_id)'));

/* ---------------------------------------------------------------- charts */
section('charts, published rankings and industry events');
say(insert('public.chart_series', ['id','key','title','chart_kind','unit','note_md','sort_order'],
  data.datacenter.map((c, i) => [q(id('chart', c.id)), q(c.id), q(c.title), q(c.type),
    q(c.unit === 'pct' ? 'pct' : c.unit === 'usd' ? 'usd' : 'count'), q(c.note), String(i)]), '(key)'));
say('\n' + insert('public.chart_points', ['series_id','ordinal','label','value','brand_id'],
  data.datacenter.flatMap((c) => c.series.map((s, i) => {
    const b = data.brands.find((x) => x.name === s.label);
    return [q(id('chart', c.id)), String(i), q(s.label), qn(s.value), b ? q(brandId(b.slug)) : 'null'];
  })), '(series_id, ordinal)'));
say('\n' + insert('public.chart_sources', ['series_id','source_id'],
  data.datacenter.flatMap((c) => (c.srcs || []).map((s) => [q(id('chart', c.id)), srcq(s)])),
  '(series_id, source_id)'));

say('\n' + insert('public.published_rankings', ['id','title','source_id','method_md','sort_order'],
  data.consumer.publishedRankings.map((r, i) =>
    [q(id('ranking', String(i))), q(r.title), srcq(r.src), q(r.method), String(i)])));
say('\n' + insert('public.published_ranking_items', ['ranking_id','ordinal','label','brand_id'],
  data.consumer.publishedRankings.flatMap((r, i) => r.items.map((it, j) => {
    const b = data.brands.find((x) => it.toLowerCase().startsWith(x.name.toLowerCase()));
    return [q(id('ranking', String(i))), String(j), q(it), b ? q(brandId(b.slug)) : 'null'];
  })), '(ranking_id, ordinal)'));

say('\n' + insert('public.industry_events',
  ['id','slug','name','date_label','location_label','why_md','source_id','starts_on'],
  data.events.map((e, i) => [q(id('event', slugify(e.name))), q(slugify(e.name)), q(e.name),
    q(e.date), q(e.location), q(e.why), srcq(e.src), 'null']), '(slug)'));

say('\ncommit;');
console.log(out.join('\n'));
const unsourcedCap = data.brands.filter((b) => b.realEstate && b.realEstate.capRate && !(b.realEstate.capSrc || []).length);
if (unsourcedCap.length) warn.push(`data finding: ${unsourcedCap.length} brands publish a cap rate with no source — ${unsourcedCap.map((b) => b.slug).join(', ')}`);
if (warn.length) process.stderr.write('NOTES (' + warn.length + '):\n' + warn.map((w) => '  ' + w).join('\n') + '\n');
